### PR TITLE
Models

### PR DESCRIPTION
**Pull request by dvdpearson**
Models created and ready to merge in develop branch.

### CODE REVIEW

**Comment by dvdpearson** [comment]
We might need to modify the models later but I think we should merge everything since it's going to be the base of our application and the following branches are going to need them.

**Comment by dvdpearson** [comment]
@paulwillyjean and @Timekiller11 since you guys are the release managers, what do you think ?

**Comment by Timekiller11** [comment]
Skimmed them, I'll inspect further later tonight but so far so good.

Unless I find something or paul has anything to say I'll go ahead and do
the merge tomorrow PM. (Leaving him enough time to see the messages)

On Mon, Jun 1, 2015 at 9:19 PM, David Pearson notifications@github.com
wrote:

> @paulwillyjean https://github.com/paulwillyjean and @Timekiller11
> https://github.com/Timekiller11 since you guys are the release
> managers, what do you think ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CtrlWebInc/laralolz/pull/1#issuecomment-107765254.

## 

Charles Forest
+1 514 296-8386

**Comment by Timekiller11** [comment]
Don't we need something that links an outing to a conference?

Theorically this isn't mandatory if we use geolocalisation then
geolocalisation isn't always available. This could be useful as an
"optional feature" and having a model for "conference_outings" could allow
to tag the same outing to multiple conferences.

Feedback?

On Tue, Jun 2, 2015 at 12:46 AM, Charles-David Forest-Le Noir <
charlesforest11@gmail.com> wrote:

> Skimmed them, I'll inspect further later tonight but so far so good.
> 
> Unless I find something or paul has anything to say I'll go ahead and do
> the merge tomorrow PM. (Leaving him enough time to see the messages)
> 
> On Mon, Jun 1, 2015 at 9:19 PM, David Pearson notifications@github.com
> wrote:
> 
> > @paulwillyjean https://github.com/paulwillyjean and @Timekiller11
> > https://github.com/Timekiller11 since you guys are the release
> > managers, what do you think ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CtrlWebInc/laralolz/pull/1#issuecomment-107765254.
> 
> ## 
> 
> Charles Forest
> +1 514 296-8386

## 

Charles Forest
+1 514 296-8386

**Comment by dvdpearson** [comment]
You're right! I'll link the conf!

**Comment by cariboufute** [comment]
According to the frontend specs we had on last meeting, the outings _are_ related to conferences. Many outings should be related to one conference (unless you think two simultaneous conferences could join for an outing, this is unlikely, but still...)

So yes, good thing to link the conference to outing!

**Comment by cariboufute** [comment]
(Sorry for the precipitous closing!)

**Pull request merged**
