### PR TITLE
Updated to Laravel 5.1, yay

### PR DESCRIPTION
**Pull request by dvdpearson**
Since Laravel 5.1 has come out today, I took some time upgrading our software to the latest and awsome version of Laravel. I kept everything from our version and applied it on 5.1 version.

Could you please take a look at the PR just for a second view ?

### CODE REVIEW

**Comment by dvdpearson** [comment]
@paulwillyjean  @Timekiller11 Could you guys look at it ?

**Comment by Timekiller11** [comment]
A bit busy tonight, I'll be testing it out tomorrow.

On Tue, Jun 9, 2015 at 8:17 PM, David Pearson notifications@github.com
wrote:

> @paulwillyjean https://github.com/paulwillyjean @Timekiller11
> https://github.com/Timekiller11 Could you guys look at it ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CtrlWebInc/laralolz/pull/4#issuecomment-110540751.

## 

Charles Forest
+1 514 296-8386

**Comment by Timekiller11** [comment]
I did the merge,  as far as I can test it's working out and there's no
critical advancement pushed yet so having everyone on 5.1 is very
important.

However we really need those Model tests...

On Tue, Jun 9, 2015 at 11:57 PM, Charles-David Forest-Le Noir <
charlesforest11@gmail.com> wrote:

> A bit busy tonight, I'll be testing it out tomorrow.
> 
> On Tue, Jun 9, 2015 at 8:17 PM, David Pearson notifications@github.com
> wrote:
> 
> > @paulwillyjean https://github.com/paulwillyjean @Timekiller11
> > https://github.com/Timekiller11 Could you guys look at it ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CtrlWebInc/laralolz/pull/4#issuecomment-110540751.
> 
> ## 
> 
> Charles Forest
> +1 514 296-8386

## 

Charles Forest
+1 514 296-8386

**Comment by paulwillyjean** [comment]
I agree about the model tests. I wanted to look at some of them to see how I could design mine and there is nothing yet.

It would be more appropriate in the models branch though.

**Comment by dvdpearson** [comment]
@paulwillyjean @Timekiller11 We're going to discuss this in the tomorrow's meeting. Thanks for the review guys !

**Comment by cariboufute** [comment]
All right, will do some tests tonight. Sorry for the wait, I have six contracts to push forward at the same time... Ouch!

**Pull request merged**
