### PR TITLE
Models

### PR DESCRIPTION
**Pull request by cariboufute**
Here, I tested the Venue model and configurated the PHPUnit tester. Added also Codeception, but this is not working yet. To test, go to the application root directory and type « phpunit tests/functional/VenueTest.php » (where the test is).

### CODE REVIEW

**Comment by dvdpearson** [comment]
Be careful @cariboufute , Since 5.1 is now PSR-2, we have to respect the line format and everything around that. It seems that you've changed the tabulation spaces (maybe related to your IDE?).

**Comment by cariboufute** [comment]
I just installed the phpfmt PSR-2 syntax check on my Sublime. The new changes in commit should be conform to PSR-2 now.

**Comment by dvdpearson** [comment]
@Timekiller11 @paulwillyjean Ready for merging guys.

**Comment by cariboufute** [comment]
Added a seeder, it's time to merge, @Timekiller11 @paulwillyjean

**Pull request merged**
